### PR TITLE
added italian translation

### PR DESCRIPTION
**Pull request by gianpispi**
Hi Hidde,
here it is the Italian translation.
I'm not quite sure what is the "What's this foot?" string. I translated it textually, but not sure if it is the way :D

Cheers

### CODE REVIEW

**Comment by hiddevdploeg** [comment]
No worries, that got in there by accident haha Thank you so much!

**Comment by hiddevdploeg** [comment]
Sorry I just noticed there are two missing in the empty strings one, could you comment these two here:

"Access Needed" = "";

"Please go to settings and allow NowPLaying to access the Microphone." = ""

**Comment by gianpispi** [comment]
"Access Needed" = "Accesso richiesto";
"Please go to settings and allow NowPLaying to access the Microphone." = "Vai in impostazioni e consenti NowPlaying di accedere al microfono.";

**Comment by hiddevdploeg** [comment]
Sorry two more... the new export feature missed some (even though they were setup correctly)

"Get Apple Music Subscription" = ""

"This will unlock more information about the songs that are playing" = ""

**Comment by gianpispi** [comment]
"Get Apple Music Subscription" = "Abbonati ad Apple Music"
"This will unlock more information about the songs that are playing" = "Sblocca più informazioni riguardo le canzoni che stanno suonando"

**Pull request merged**
